# Generated by Django 4.1.2 on 2023-10-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=100)),
                ('Author_name', models.CharField(max_length=100)),
                ('Book_img', models.CharField(max_length=1000)),
                ('Book_pdf', models.FileField(upload_to='pdfs/')),
                ('Nutritional_content', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Books2',
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
