# Generated by Django 4.1.2 on 2023-10-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_library', '0003_books3_delete_books2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books3',
        ),
    ]
