# Generated by Django 4.1.2 on 2023-10-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Digital_library', '0004_delete_books3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=50)),
                ('Author_name', models.CharField(max_length=50)),
                ('Book_img', models.CharField(max_length=100)),
                ('Book_pdf', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
    ]
