# Generated by Django 4.1.2 on 2023-10-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_library', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Book_img',
            field=models.CharField(max_length=200),
        ),
    ]
