# Generated by Django 4.1.2 on 2023-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_library', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Author_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
